import { initContactForm } from './js/contactForm.js';
import { initCursor } from './js/cursor.js';
import { initHeroParallax } from './js/heroParallax.js';
import { initHeroWord } from './js/heroWord.js';
import { initMobileMenu } from './js/mobileMenu.js';
import { initNavigation } from './js/navigation.js';
import { initReveal } from './js/reveal.js';
import { initTiltCards } from './js/tiltCards.js';
import { initWorkFilter } from './js/workFilter.js';
import { renderPage } from './renderPage.js';

renderPage();
initCursor();
initNavigation();
initMobileMenu();
initReveal();
initTiltCards();
initWorkFilter();
initContactForm();
initHeroWord();
initHeroParallax();
